global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ticket-api"
    metrics_path: /metrics
    basic_auth:
      username: "${METRICS_USER}"
      password: "${METRICS_PASSWORD}"
    static_configs:
      - targets: ["${TICKET_API_HOST}"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "ticket-api-railway"
